# Generated by Django 4.2.1 on 2023-05-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vtuapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="network",
            name="corporate_data_vending_medium",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CHEAPESTDATASUB", "CHEAPESTDATASUB"),
                    ("QTopUp", "QTopUp"),
                    ("UWS", "UWS"),
                    ("MSORG_DEVELOPED_WEBSITE_3", "MSORG Developed Website 3"),
                    ("ALAGUSIY", "ALAGUSIY"),
                    ("SMEIFY", "SMEIFY"),
                    ("SMEPLUG", "SMEPLUG"),
                    ("MSORG_DEVELOPED_WEBSITE", "MSORG Developed Website 1"),
                    ("SIM_SERVER", "SIM_SERVER"),
                    ("SIMHOST_NG", "SIMHOSTNG.COM"),
                    ("SIMHOST", "USSD.SIMHOSTING"),
                    ("MSORG_DEVELOPED_WEBSITE_2", "MSORG Developed Website 2"),
                    ("SMS", "SMS"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="gifting_vending_medium",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CHEAPESTDATASUB", "CHEAPESTDATASUB"),
                    ("QTopUp", "QTopUp"),
                    ("UWS", "UWS"),
                    ("MSORG_DEVELOPED_WEBSITE_3", "MSORG Developed Website 3"),
                    ("ALAGUSIY", "ALAGUSIY"),
                    ("SMEIFY", "SMEIFY"),
                    ("SMEPLUG", "SMEPLUG"),
                    ("MSORG_DEVELOPED_WEBSITE", "MSORG Developed Website 1"),
                    ("SIM_SERVER", "SIM_SERVER"),
                    ("SIMHOST_NG", "SIMHOSTNG.COM"),
                    ("SIMHOST", "USSD.SIMHOSTING"),
                    ("MSORG_DEVELOPED_WEBSITE_2", "MSORG Developed Website 2"),
                    ("SMS", "SMS"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
